name: ${project.name}
description: ${project.description}
author: AlbireoX
version: ${release.number}
website: ${project.url}

main: net.celestiusmc.celestiussides.CelestiusSides

commands:
  race:
    description: The race base command.
    usage: /race 
    
permissions:
  sides.setspawn:
    description: Set the spawn of a race.
    default: op